# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jah}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcos Piccinini"]
  s.date = %q{2009-09-29}
  s.default_executable = %q{jah}
  s.description = %q{talk to your machines}
  s.email = %q{x@nofxx.com}
  s.executables = ["jah"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "bin/jah",
     "jah.gemspec",
     "lib/jah.rb",
     "lib/jah.yaml.template",
     "lib/jah/agent.rb",
     "lib/jah/agents/dump.rb",
     "lib/jah/agents/post.rb",
     "lib/jah/agents/xmpp.rb",
     "lib/jah/cli.rb",
     "lib/jah/command.rb",
     "lib/jah/commands/cpu.rb",
     "lib/jah/commands/disk.rb",
     "lib/jah/commands/mem.rb",
     "lib/jah/commands/net.rb",
     "lib/jah/commands/prok.rb",
     "lib/jah/commands/services.rb",
     "lib/jah/commands/who.rb",
     "lib/jah/command.rb",
     "lib/jah/commands/admin.rb",
     "lib/jah/commands/extra.rb",
     "lib/jah/commands/pub.rb",
     "lib/jah/commands/status.rb",
     "lib/jah/god.rb",
     "lib/jah/install.rb",
     "lib/locales/en_us.yml",
     "lib/locales/pt_br.yml",
     "lib/locales/pt_br_gostosa.yml",
     "lib/locales/pt_br_mano.yml",
     "lib/locales/pt_br_mineiro.yml",
     "spec/console",
     "spec/jah_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/nofxx/jah}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{be omnipresent...}
  s.test_files = [
    "spec/jah_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<blather>, [">= 0"])
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<blather>, [">= 0"])
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<blather>, [">= 0"])
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end
