# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jah}
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcos Piccinini"]
  s.date = %q{2009-11-26}
  s.default_executable = %q{jah}
  s.description = %q{Talk to your machines. Like a God.}
  s.email = %q{x@nofxx.com}
  s.executables = ["jah"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "bin/jah",
     "jah.gemspec",
     "lib/jah.rb",
     "lib/jah/act_pkg.rb",
     "lib/jah/act_pkg/apt.rb",
     "lib/jah/act_pkg/base.rb",
     "lib/jah/act_pkg/emerge.rb",
     "lib/jah/act_pkg/pacman.rb",
     "lib/jah/act_pkg/pkg.rb",
     "lib/jah/act_pkg/ports.rb",
     "lib/jah/act_pkg/slack.rb",
     "lib/jah/act_pkg/urpm.rb",
     "lib/jah/act_pkg/yum.rb",
     "lib/jah/act_pkg/zypp.rb",
     "lib/jah/agent.rb",
     "lib/jah/agents/dump.rb",
     "lib/jah/agents/post.rb",
     "lib/jah/agents/xmpp.rb",
     "lib/jah/cli.rb",
     "lib/jah/command.rb",
     "lib/jah/commands/admin.rb",
     "lib/jah/commands/cpu.rb",
     "lib/jah/commands/disk.rb",
     "lib/jah/commands/extra.rb",
     "lib/jah/commands/mem.rb",
     "lib/jah/commands/netstat.rb",
     "lib/jah/commands/packages.rb",
     "lib/jah/commands/prok.rb",
     "lib/jah/commands/services.rb",
     "lib/jah/commands/status.rb",
     "lib/jah/commands/who.rb",
     "lib/jah/history.rb",
     "lib/jah/install.rb",
     "lib/jah/opt.rb",
     "lib/jah/prayer.rb",
     "lib/locales/en_us.yml",
     "lib/locales/pt_br.yml",
     "lib/locales/pt_br_gostosa.yml",
     "lib/locales/pt_br_mano.yml",
     "lib/locales/pt_br_mineiro.yml",
     "spec/console",
     "spec/jah/act_pkg/apt_spec.rb",
     "spec/jah/act_pkg/pacman_spec.rb",
     "spec/jah/act_pkg/pkg_spec.rb",
     "spec/jah/act_pkg/ports_spec.rb",
     "spec/jah/act_pkg/yum_spec.rb",
     "spec/jah/act_pkg_spec.rb",
     "spec/jah/agent_spec.rb",
     "spec/jah/agents/xmpp_spec.rb",
     "spec/jah/cli_spec.rb",
     "spec/jah/command_spec.rb",
     "spec/jah/commands/cpu_spec.rb",
     "spec/jah/commands/disk_spec.rb",
     "spec/jah/commands/mem_spec.rb",
     "spec/jah/commands/netstat_spec.rb",
     "spec/jah/commands/prok_spec.rb",
     "spec/jah/commands/who_spec.rb",
     "spec/jah/history_spec.rb",
     "spec/jah/install_spec.rb",
     "spec/jah/opt_spec.rb",
     "spec/jah/prayer_spec.rb",
     "spec/jah_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/nofxx/jah}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Be omnipresent...}
  s.test_files = [
    "spec/jah/cli_spec.rb",
     "spec/jah/agents/xmpp_spec.rb",
     "spec/jah/install_spec.rb",
     "spec/jah/commands/mem_spec.rb",
     "spec/jah/commands/cpu_spec.rb",
     "spec/jah/commands/who_spec.rb",
     "spec/jah/commands/netstat_spec.rb",
     "spec/jah/commands/disk_spec.rb",
     "spec/jah/commands/prok_spec.rb",
     "spec/jah/agent_spec.rb",
     "spec/jah/command_spec.rb",
     "spec/jah/act_pkg/yum_spec.rb",
     "spec/jah/act_pkg/apt_spec.rb",
     "spec/jah/act_pkg/pkg_spec.rb",
     "spec/jah/act_pkg/ports_spec.rb",
     "spec/jah/act_pkg/pacman_spec.rb",
     "spec/jah/opt_spec.rb",
     "spec/jah/act_pkg_spec.rb",
     "spec/jah/prayer_spec.rb",
     "spec/jah/history_spec.rb",
     "spec/jah_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<blather>, [">= 0.4.7"])
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<blather>, [">= 0.4.7"])
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<blather>, [">= 0.4.7"])
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

